version: "3.0"

services:
  spark:
    build: ./dockers/spark
    command: sleep infinity
  zeppelin:
    build: ./dockers/zeppelin
    # network_mode: "host"
    ports:
      - 8080:8080
    container_name: zeppelin
    volumes:
      - ./dockers/zeppelin/conf/interpreter-setting.json:/opt/zeppelin/interpreter/spark/interpreter-setting.json:ro
      - ./dockers/zeppelin/conf/shiro.ini:/opt/zeppelin/conf/shiro.ini:ro
      - ./dockers/zeppelin/conf/certificate.pem:/opt/zeppelin/spark/k8s_conf/certificate.pem:ro
      - ./dockers/zeppelin/conf/spark_token:/opt/zeppelin/spark/k8s_conf/spark_token:ro
      - ./notebook:/opt/zeppelin/notebook

  s3:
    image: "minio/minio:latest"
    volumes:
      - ./.storage/s3:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: "root"
      MINIO_SECRET_KEY: "root12345"
    command: server /data --console-address ":9001"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://127.0.0.1:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
